title: LibRetro - GitHub
email: prateek@prateekkumar.in
description: >- # this means to ignore newlines until "baseurl:"
  This website contains list of all the open source repositories on github by Libretro.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://libretro.com" # the base hostname & protocol for your site, e.g. http://example.com
about_url: https://https://libretro.com
twitter_username: libretro
github_username: libretro
author: libretro
lang: en-IN
google_analytics: 

timezone: Europe/Istanbul

# Build settings
markdown: kramdown
plugins:
#  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
#  - jekyll-mentions
#  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md
  - screenshot.png
